### ISSUE TITLE
dataset for freebase-likq sample does not exist

### ISSUE THREAD

**Issue by TaviTruman** [Microsoft/GraphEngine#341] opened 2022-06-12 21:46 UTC
FireBase Sample dataset does not exist.

https://graphengine.blob.core.windows.net/public-data"
freebase-full-dataset-20170410.zip file does not exist.

System.AggregateException
  HResult=0x80131500
  Message=One or more errors occurred. (The remote server returned an error: (404) The specified resource does not exist..)
  Source=System.Private.CoreLib
  StackTrace:
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at freebase_likq.Program.DownloadDataFile() in O:\TrinityGraphEngine\GraphEngine\samples\freebase-likq\freebase-likq\Program.cs:line 122
   at freebase_likq.Program.Initialize() in O:\TrinityGraphEngine\GraphEngine\samples\freebase-likq\freebase-likq\Program.cs:line 58
   at freebase_likq.Program.Main(String[] args) in O:\TrinityGraphEngine\GraphEngine\samples\freebase-likq\freebase-likq\Program.cs:line 29

  This exception was originally thrown at this call stack:
    [External Code]

Inner Exception 1:
WebException: The remote server returned an error: (404) The specified resource does not exist..

**Comment by TaviTruman** [comment] 2022-06-12 21:49
This is a duplicate - please detele!

**Comment by shaobin** [comment] 2022-06-14 11:26
This is a duplicate of 341. This one will be closed.

**Closed as completed by shaobin** 2022-06-14 11:26 UTC
